const assert = require('node:assert/strict')
const m = require('../Model.js')
const b = { key: 'BAT0', supported: true, enabled: false, percentage: 79, state: 5, end: 80, start: 75 }
assert.equal(m.holding(b, false), false)
assert.equal(m.status(b, false), 'Plugged in · charge paused')
assert.match(m.explanation(b, false), /not active/)
assert.equal(m.holding({...b, enabled: true}, false), true)
assert.equal(m.holding({...b, enabled: true}, true), false)
assert.equal(m.holding({...b, enabled: true, mismatch: true}, false), false)
assert.match(m.explanation({...b, enabled: true, percentage: 100}, false), /not actively drain/)
assert.match(m.explanation({...b, mode: 'full'}, false), /15 seconds/)
assert.equal(m.status({...b, state: 1, rate: 0}, false), 'Charging to full')
assert.equal(m.duration(0), '—')
assert.equal(m.duration(3660), '1h 1m')
assert.equal(m.percent(null), '—')
assert.equal(m.limitLabel({...b, end: null}), 'Protect battery')
assert.match(m.explanation({...b, supported: false}, false), /not available/)
assert.equal(m.protectionAction({...b, enabled: true}), 'off')
assert.equal(m.protectionAction({...b, enabled: false}), 'protect')
assert.match(m.explanation({...b, mode: 'off'}, false), /until you turn the limit on again/)
assert.equal(m.fullChargeActive({...b, mode: 'full', enabled: false}), true)
assert.equal(m.fullChargeAction({...b, mode: 'full', enabled: false}), 'protect')
assert.equal(m.fullChargeAction({...b, mode: 'protect', enabled: true}), 'full')
assert.equal(m.fullChargeActive({...b, mode: 'off', enabled: false}), false)
assert.equal(m.fullChargeActive({...b, mode: 'full', enabled: true}), false)
console.log('22 battery presentation regression checks passed')
assert.equal(m.status({...b, enabled: true, state: 3}, false), 'Empty')
assert.equal(m.holding({...b, enabled: true, state: 3}, false), false)
assert.equal(m.percent(NaN), '—')
assert.equal(m.percent(Infinity), '—')
assert.equal(m.nextControl(0, 1, [0, 2, 3], false), 0)
assert.equal(m.nextControl(0, 1, [0, 2, 3], true), 2)
assert.equal(m.nextControl(2, -1, [0, 2, 3], true), 0)
assert.equal(m.nextControl(3, 1, [0, 2, 3], true), 3)
assert.equal(m.nextControl(1, 1, [0, 2, 3], true), 0)
assert.equal(m.nextControl(0, 1, [], true), -1)
console.log('10 additional review regression assertions passed')
// Connecting AC while the battery is inside its protection band must be visible
// without implying that current is flowing into the battery.
const held = {...b, enabled: true, percentage: 77}
assert.equal(m.status(held, false), 'Plugged in · charge paused')
assert.equal(m.batteryIcon(held, false), '󰚥')
assert.equal(m.batteryIcon({...held, state: 1}, false), '󰂄')
assert.notEqual(m.batteryIcon({...held, state: 2}, true), '󰚥')
assert.equal(m.status({...held, state: 2}, true), 'On battery')
assert.equal(m.batteryIcon({...b, state: 4, percentage: 100}, false), '󰚥')
assert.match(m.explanation(held, false), /Stops charging at 80%.*Resumes below 75%/)
console.log('7 plugged-in presentation regression assertions passed')
